version: '3.9'
services:
  checker-psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: checker_db
      POSTGRES_USER: checkwr
      POSTGRES_PASSWORD: 12987wq
    volumes:
      - /tmp:/var/lib/postgresql/data2
    ports:
      - "2020:5432"

  redis:
    container_name: "redis"
    image: "redis:alpine"
    #    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "1234:6379"
#    volumes:
#      - $PWD/configs/redis.conf:/usr/local/etc/redis/redis.conf

